### ISSUE TITLE
Make Scan Over Blocks Case Insensitive

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISNeutronMuon/InstrumentScripts#24]
Block names used in a scan should not be case sensitive. 

Note that https://github.com/ISISComputingGroup/IBEX/issues/4136 will introduce an all uppercase alias for all blocks, which can be used for this purpose.

**Comment by rprospero** [comment]
Note that the populate() utility command already creates three motion objects for different cases:  upper, lower, and original.

**Comment by rprospero** [comment]
Fixed in PR #37
