### ISSUE TITLE
Prevent useless wiring table changes in SANS

### ISSUE THREAD

**Issue by rprospero** [ISISNeutronMuon/InstrumentScripts#27]
Originally, the SANS library stored the current DAE mode so that changing into the current mode could be implemented as a no-op.  This functionality was removed because a user changed the wiring table outside of the SANS library and chaos ensued trying to get the library back in sync with reality.  It was also felt that changing the wiring table was quick enough to warrant the extraneous changes.

Unfortunately, that decision was premature and changing the wiring tables is becoming a serious bottleneck.  Furthermore, changing the wiring table outside of the SANS library during a SANS experiment is unjustified enough that users attempting it will only have themselves to blame for the problems that follow.

Therefore, we should re-implement the caching.

**Comment by John-Holt-Tessella** [comment]
If you could query `genie_python` to find what the current table is, instead of caching, would that be better? If so we can add the genni_python command to do this. (Please ask if you need features)

**Comment by rprospero** [comment]
That would certainly be the optimal solution.  We may implementing the caching for now, but switch to querying `genie_python` when that option becomes available.

**Comment by John-Holt-Tessella** [comment]
I have created https://github.com/ISISComputingGroup/IBEX/issues/4330 did you want us to prioritise this? How critical do you think it is?

**Comment by rprospero** [comment]
It's not a top priority.  I've already re-implemented the caching, so that will handle most of the issues.  If it's something that can be popped off quickly, we'd appreciate having it before the start of the cycle.  On the other hand, if there's any question about how long it will take, then we can absolutely wait until the next shut down.

**Comment by FreddieAkeroyd** [comment]
The wiring, detector and spectra tables are already available as PVs e.g. 

 get_pv("IN:LARMOR:DAE:WIRING_FILE")
 get_pv("IN:LARMOR:DAE:DETECTOR_FILE")
 get_pv("IN:LARMOR:DAE:SPECTRA_FILE")

**Comment by FreddieAkeroyd** [comment]
I will also check wiring change performance on ZOOM - if the tables haven't changed then they are not reloaded, however I do use an md5checksum to see if they have changed and maybe that file read to calculate the checksum has become slow? If so, i could probably change to  

if  (filename same) && (modification time same) && (size same)   then assume same
else  compare checksum: if checksum same, update details and return else reload file. 

Though i could even skip the checksum and just reload, it would mean if there was a no change edit you would reload the file but that will not happen very often i expect.

**Comment by FreddieAkeroyd** [comment]
On ZOOM trying to change_tables() to the current wiring table takes only 1 second

**Comment by rprospero** [comment]
This is now handled in the upcoming september branch

**Comment by rprospero** [comment]
This should be handled by pr #35
