### ISSUE TITLE
Discussion: Remove populate

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISNeutronMuon/InstrumentScripts#60]
As a developer I would recommend getting rid of populate

Its purpose is to create variables which can be used instead of block names so that scan can be written: `scan(block, ...` instead of `scan("block", ...`. But it comes with caveats that when the user changes config they must remember to rerun populate to get new blocks and it is different to the recommended way of running `g.cset` i.e. `cset("block", value)`. However I do not know the history and so would like to understand its motivation.

### Acceptance Criteria

1. A decision is made on populate and the decision is recorder.
1. Any needed tickets are generated to make the changes

**Comment by ChrisM-S** [comment]
Could be worth seeing how use of this would play out in the script server too... not sure if this would work well.  Something seems wrong about fixing a syntax preference with assignments…

**Comment by ThomasLohnert** [comment]
Solved by https://github.com/ISISComputingGroup/IBEX/issues/5401, closing issue.
